"""Every tunable knob in one module."""

HTTP_TIMEOUT_S = 20
HTTP_RETRIES = 2
HTTP_BACKOFF_S = 1.0
BREAKER_THRESHOLD = 3
MAX_ENTRIES_PER_FEED = 25
MAX_SITEMAP_PAGES = 8
ARXIV_DELAY_S = 3
BLOG_BODY_MIN = 1500
JS_WALLED_DOMAINS = {"openai.com"}

MIN_CHARS = {"blog": 100, "newsroom": 100, "github": 400, "arxiv": 150,
             "social": 60}
RELEASE_FEED_MIN_CHARS = 50

X_POST_COST_USD = 0.005
X_USER_COST_USD = 0.010
X_MAX_POSTS_PER_ACCOUNT = 20
X_MAX_POSTS_PER_RUN = 1000
X_RUN_BUDGET_USD = 8.00
X_MAX_USER_LOOKUPS = 60
X_BIO_REOBSERVE_DAYS = 7

MAX_INSIGHTS_PER_DOC = 5

EXPANSION_WINDOW_DAYS = 365

CLUSTER_THETA = 0.4

RECENCY_SCALE_DAYS = 30.0
NEUTRAL_RECENCY = 0.5

TEST_FRAC = 0.30
RANDOM_SEED = 42
